model:
  llm_model_path: 'quantised_model/Phi-3-mini-4k-instruct-q4.gguf'
  embedding_model_hf_name: 'sentence-transformers/all-mpnet-base-v2' #'Alibaba-NLP/gte-base-en-v1.5'
  ctx_len: 2048
  no_of_threads: 8
  temperature: 0.9
  max_tokens: 200
  repeat_penalty: 1.5
  top_p: 0.5

data:
  qa_file_path: 'data/qa_pairs_drop_duplicates.json'
  additional_context_path: 'data/additional_context.json'
  chunk_overlap: 50
  chunk_size: 350 #limited by local compute
  

vector_db:
  name: 'milvus_db'
  host_url: 'localhost'
  port_number: '19530'
  fin_qa_collection_name: 'qa_collection'
  extra_fin_context_collection_name: 'context_collection'

gradio:
  title: 'ConvFinQA RAG System'
